namespace KartPaymentService.Domain.Webhooks;

/// <summary>
/// ddd-model.md: the dedup ledger for asynchronous gateway confirmations, keyed on the gateway's
/// own <see cref="GatewayEventId"/> (never generated by this service) - same shape/purpose as
/// `kart-delivery-tracking-service`'s `WebhookDedupEntry`, applied here to the payment-gateway
/// analogue. No domain events published externally - this is Payment's own internal ingestion
/// ledger.
/// </summary>
public sealed class GatewayWebhookEvent
{
    public string GatewayEventId { get; private set; } = string.Empty;

    public string Gateway { get; private set; } = string.Empty;

    public Guid PaymentIntentId { get; private set; }

    public GatewayEventType EventType { get; private set; }

    /// <summary>Which PaymentIntentStatus transition (or refund/chargeback effect) this event actually caused, once processed.</summary>
    public string? AppliedTransition { get; private set; }

    public DateTimeOffset ReceivedAt { get; private set; }

    public DateTimeOffset? ProcessedAt { get; private set; }

    public DateTimeOffset UpdatedAt { get; private set; }

    public string CreatedBy { get; private set; } = "system:payment-gateway-webhook-consumer";

    public string UpdatedBy { get; private set; } = "system:payment-gateway-webhook-consumer";

    /// <summary>EF Core materialization only.</summary>
    private GatewayWebhookEvent()
    {
    }

    public static GatewayWebhookEvent Receive(string gatewayEventId, string gateway, Guid paymentIntentId, GatewayEventType eventType, DateTimeOffset now)
        => new()
        {
            GatewayEventId = gatewayEventId,
            Gateway = gateway,
            PaymentIntentId = paymentIntentId,
            EventType = eventType,
            ReceivedAt = now,
            UpdatedAt = now,
        };

    public void MarkProcessed(string appliedTransition, DateTimeOffset now)
    {
        AppliedTransition = appliedTransition;
        ProcessedAt = now;
        UpdatedAt = now;
    }
}
