// <auto-generated />
using System;
using System.Collections.Generic;
using KartPaymentService.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace KartPaymentService.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(PaymentDbContext))]
    partial class PaymentDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("KartPaymentService.Domain.Idempotency.IdempotencyRecord", b =>
                {
                    b.Property<string>("IdempotencyKey")
                        .HasColumnType("text")
                        .HasColumnName("idempotency_key");

                    b.Property<string>("Endpoint")
                        .HasColumnType("text")
                        .HasColumnName("endpoint");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("RequestPayloadHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("request_payload_hash");

                    b.Property<string>("StoredResponse")
                        .HasColumnType("jsonb")
                        .HasColumnName("stored_response");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.HasKey("IdempotencyKey", "Endpoint");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("idx_idempotency_keys_expiry");

                    b.ToTable("idempotency_keys", (string)null);
                });

            modelBuilder.Entity("KartPaymentService.Domain.Payments.PaymentIntent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("GatewayToken")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("gateway_token");

                    b.Property<string>("OrderId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("order_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("TxnId")
                        .HasColumnType("text")
                        .HasColumnName("txn_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.ComplexProperty<Dictionary<string, object>>("CapturedAmount", "KartPaymentService.Domain.Payments.PaymentIntent.CapturedAmount#Money", b1 =>
                        {
                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric(12,2)")
                                .HasColumnName("captured_amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("currency");
                        });

                    b.HasKey("Id");

                    b.HasIndex("OrderId")
                        .IsUnique();

                    b.ToTable("payment_intents", (string)null);
                });

            modelBuilder.Entity("KartPaymentService.Domain.Webhooks.GatewayWebhookEvent", b =>
                {
                    b.Property<string>("GatewayEventId")
                        .HasColumnType("text")
                        .HasColumnName("gateway_event_id");

                    b.Property<string>("AppliedTransition")
                        .HasColumnType("text")
                        .HasColumnName("applied_transition");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("event_type");

                    b.Property<string>("Gateway")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("gateway");

                    b.Property<Guid>("PaymentIntentId")
                        .HasColumnType("uuid")
                        .HasColumnName("payment_intent_id");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_at");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.HasKey("GatewayEventId");

                    b.HasIndex("PaymentIntentId", "ReceivedAt")
                        .HasDatabaseName("idx_gateway_webhook_events_intent");

                    b.ToTable("gateway_webhook_events", (string)null);
                });

            modelBuilder.Entity("KartPaymentService.Infrastructure.Persistence.PaymentOutboxEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AggregateId")
                        .HasColumnType("uuid")
                        .HasColumnName("aggregate_id");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("event_type");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<string>("TraceParent")
                        .HasColumnType("text")
                        .HasColumnName("trace_parent");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.HasIndex("OccurredAt")
                        .HasDatabaseName("idx_payment_outbox_unpublished")
                        .HasFilter("published_at IS NULL");

                    b.ToTable("payment_outbox_events", (string)null);
                });

            modelBuilder.Entity("KartPaymentService.Domain.Payments.PaymentIntent", b =>
                {
                    b.OwnsOne("KartPaymentService.Domain.Payments.ChargebackRecord", "Chargeback", b1 =>
                        {
                            b1.Property<Guid>("PaymentIntentId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric(12,2)")
                                .HasColumnName("chargeback_amount");

                            b1.Property<string>("ChargebackId")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("chargeback_id");

                            b1.Property<string>("Reason")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("chargeback_reason");

                            b1.Property<DateTimeOffset>("ReceivedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("chargeback_received_at");

                            b1.HasKey("PaymentIntentId");

                            b1.ToTable("payment_intents");

                            b1.WithOwner()
                                .HasForeignKey("PaymentIntentId");
                        });

                    b.OwnsMany("KartPaymentService.Domain.Payments.Refund", "Refunds", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric(12,2)")
                                .HasColumnName("amount");

                            b1.Property<string>("CreatedBy")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("created_by");

                            b1.Property<Guid>("PaymentIntentId")
                                .HasColumnType("uuid")
                                .HasColumnName("payment_intent_id");

                            b1.Property<DateTimeOffset>("RequestedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("requested_at");

                            b1.Property<string>("Status")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("status");

                            b1.Property<DateTimeOffset>("UpdatedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("updated_at");

                            b1.Property<string>("UpdatedBy")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("updated_by");

                            b1.HasKey("Id");

                            b1.HasIndex("PaymentIntentId")
                                .HasDatabaseName("idx_refunds_intent_succeeded")
                                .HasFilter("status = 'succeeded'");

                            b1.ToTable("refunds", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("PaymentIntentId");
                        });

                    b.Navigation("Chargeback");

                    b.Navigation("Refunds");
                });
#pragma warning restore 612, 618
        }
    }
}
